'use strict';
const {app,BrowserWindow,ipcMain,screen,Tray,Menu,nativeImage,clipboard,session}=require('electron');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {defaults,sanitizeSettings,parseYouTube,confine,anchors,nearest,dockPoint}=require('./core');
const {playerOperation}=require('./player-operation');
const {roundedShape,springProgress}=require('./window-motion');
const {NativeMotion}=require('./native-motion');
const playerCSS=['shared.css','controller.css','player.css','material.css'].map(name=>fs.readFileSync(path.join(__dirname,'ui',name),'utf8')).join('\n');
const smoke=process.argv.includes('--smoke-test'),youtubeProbe=process.argv.includes('--youtube-probe');
const nativeDrag=process.argv.includes('--native-drag');
const inputCheck=process.argv.includes('--input-check');
const probeArg=process.argv.indexOf('--probe-url');const probeInline=process.argv.find(arg=>arg.startsWith('--probe-url='));const probeUrl=probeInline?probeInline.slice('--probe-url='.length):probeArg>=0?process.argv[probeArg+1]:'https://www.youtube.com/watch?v=M7lc1UVf-VE';
const reportArg=process.argv.indexOf('--report');const reportDir=reportArg>=0?path.resolve(process.argv[reportArg+1]):path.resolve(__dirname,'../outputs/native-check');
app.setName('Moro');
if(smoke||youtubeProbe||inputCheck)app.setPath('userData',path.join(app.getPath('temp'),'moro-check-'+process.pid));
app.setAppUserModelId('local.moro.player');
app.commandLine.appendSwitch('autoplay-policy','no-user-gesture-required');
if(!app.requestSingleInstanceLock()){app.quit();}else{
let player,controller,tray,settings={...defaults},kind='empty',closing=false,hitRegions=[],ignore=null,drag=false,spring=null,hover=null,pollBusy=false,lastState={},saveTimer,mediaGeneration=0;
let dock=null,dockSignature='',controllerOpen=false,controllerVisible=false,controllerLastSeen=Date.now(),ctrlHeld=false,interactionSignature='';
let dragRevision=0;
let motionDriver,playerWanted=false,desktopProtection,resizeGesture=false,resizeRunning=false,resizeAnchor=null,resizeTimer=null,resizeStep=null,resizeTarget=null,resizeState=null,lastResizeReport=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const uiFile=name=>pathToFileURL(path.join(__dirname,'ui',name)).href;
const assets=name=>pathToFileURL(path.join(__dirname,'assets',name)).href;
const settingsFile=()=>path.join(app.getPath('userData'),'settings.json');
const validWindow=w=>w&&!w.isDestroyed();
function send(w,channel,data){if(validWindow(w)&&!w.webContents.isDestroyed())w.webContents.send(channel,data);}
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{fs.mkdirSync(app.getPath('userData'),{recursive:true});fs.writeFileSync(settingsFile(),JSON.stringify(settings,null,2));}catch{}},300);}
function notice(text){controllerLastSeen=Date.now()+2500;if(kind!=='empty'&&player.isVisible())send(player,'moro:notice',text);else{setDockVisible(true);send(controller,'moro:notice',text);}}
function sender(e,w){return validWindow(w)&&e.sender===w.webContents&&e.senderFrame===w.webContents.mainFrame;}
function trustedPlayer(e){if(!sender(e,player))return false;const url=e.senderFrame.url;return url===uiFile('player.html')||/^https:\/\/www\.youtube-nocookie\.com\/embed\/[\w-]{11}(\?|$)/.test(url);}
function trustedController(e){return sender(e,controller)&&e.senderFrame.url===uiFile('controller.html');}
function area(){return screen.getDisplayMatching(player.getBounds()).workArea;}
function publishDock(){if(!dock)return;const payload={x:dock.point.x-dock.bounds.x,y:dock.point.y-dock.bounds.y,visible:controllerVisible,pinned:settings.gooPinned};const signature=JSON.stringify(payload);if(signature!==dockSignature){dockSignature=signature;send(controller,'moro:dock',payload);}}
function setDockVisible(visible){controllerVisible=!!visible&&!drag&&!spring&&controllerOpen;publishDock();if(!validWindow(controller))return;if(controllerVisible){if(!controller.isVisible())controller.showInactive();}else{hitRegions=[];if(controller.isVisible())controller.hide();}}
function placeController(display){if(!validWindow(controller)||!validWindow(player))return;display=display||screen.getPrimaryDisplay();const a=display.workArea,width=Math.min(400,a.width),height=Math.min(600,a.height),bounds={x:a.x+a.width-width,y:a.y+a.height-height,width,height},point={x:a.x+a.width-40,y:a.y+a.height-23};const current=controller.getBounds();if(Object.keys(bounds).some(key=>bounds[key]!==current[key]))controller.setBounds(bounds,false);dock={point,bounds};publishDock();}
function updateInteraction(cursor=screen.getCursorScreenPoint(),force=false){if(!validWindow(player))return;const p=player.getBounds(),inside=player.isVisible()&&((ctrlHeld&&resizeGesture)||(cursor.x>=p.x&&cursor.y>=p.y&&cursor.x<p.x+p.width&&cursor.y<p.y+p.height));const nextIgnore=!ctrlHeld;if(ignore!==nextIgnore){player.setIgnoreMouseEvents(nextIgnore);ignore=nextIgnore;}const state={ctrl:ctrlHeld,inside};const signature=JSON.stringify(state);if(force||signature!==interactionSignature){interactionSignature=signature;send(player,'moro:interaction',state);}hover=inside;}
function setControlHeld(held){ctrlHeld=held===true;updateInteraction(undefined,true);}
function setPlayerVisible(visible,focus=false){playerWanted=visible;if(!validWindow(player))return;if(visible){if(player.isMinimized())player.restore();if(focus)player.show();else player.showInactive();}else player.hide();}
function preservePlayerVisibility(){if(closing||!playerWanted||!validWindow(player))return;if(player.isMinimized()){if(motionDriver?.available)motionDriver.reveal(player.getNativeWindowHandle().readBigUInt64LE().toString());else player.restore();return;}if(!player.isVisible())player.showInactive();if(!player.isAlwaysOnTop())player.setAlwaysOnTop(true,'floating');}
function presentController(){placeController();controllerOpen=true;setDockVisible(true);controller.show();send(controller,'moro:open');}
function cancelMotion(){if(motionDriver)motionDriver.cancel();resizeRunning=false;resizeStep=null;send(player,'moro:resize-clock',false);resizeTarget=null;resizeState=null;resizeAnchor=null;clearInterval(resizeTimer);resizeTimer=null;if(spring){if(spring.timer)clearInterval(spring.timer);spring=null;}}
function updateShape(){if(validWindow(player)){const b=player.getBounds();player.setShape(roundedShape(b.width,b.height,settings.radius));}}
function moveTo(point){cancelMotion();if(!validWindow(player))return;const dest=confine({...player.getBounds(),...point},area()),start=player.getPosition(),started=performance.now();let last=start;
  if(motionDriver?.available){const request=motionDriver.move(player.getNativeWindowHandle().readBigUInt64LE().toString(),screen.dipToScreenPoint({x:dest.x,y:dest.y}),settings);spring=request;request.finished.then(report=>{if(spring!==request)return;spring=null;if(report.completed&&!drag&&validWindow(player)){placeController();controllerLastSeen=Date.now();setDockVisible(true);}});return;}
  const fallback={timer:null};spring=fallback;fallback.timer=setInterval(()=>{if(!validWindow(player)||drag)return cancelMotion();const seconds=(performance.now()-started)/1000,progress=springProgress(seconds,settings.response,settings.bounce),position=[Math.round(start[0]+(dest.x-start[0])*progress),Math.round(start[1]+(dest.y-start[1])*progress)];
    if(position[0]!==last[0]||position[1]!==last[1])player.setPosition(...position,false);last=position;
    if(seconds>1.2||(seconds>.25&&Math.hypot(dest.x-position[0],dest.y-position[1])<.5)){player.setPosition(dest.x,dest.y,false);cancelMotion();placeController();controllerLastSeen=Date.now();setDockVisible(true);}
  },16);
}
function center(){if(kind!=='empty')setPlayerVisible(true);moveTo(anchors(player.getBounds(),area())[4]);}
function beginDrag(){if(drag)return;dragRevision++;cancelMotion();drag=true;send(player,'moro:dragging',true);setDockVisible(false);}
function endDrag(){if(!drag)return;const revision=dragRevision;
  // Return from WM_EXITSIZEMOVE before reading the final bounds or moving a HWND.
  setImmediate(()=>{if(!drag||revision!==dragRevision||!validWindow(player))return;drag=false;send(player,'moro:dragging',false);const current=player.getBounds(),b=confine(current,area()),n=nearest(b,area());controllerLastSeen=Date.now();
    if(settings.magnet>0&&n.d<settings.magnet)moveTo(n);
    else if(b.x!==current.x||b.y!==current.y)moveTo(b);
    else{placeController();setDockVisible(true);}
  });
}
function finishResize(){resizeRunning=false;resizeStep=null;send(player,'moro:resize-clock',false);clearInterval(resizeTimer);resizeTimer=null;updateShape();if(!resizeGesture){resizeAnchor=null;send(player,'moro:resize-end');}placeController();interactionSignature='';}
function resizePlayer(width){
  if(!resizeAnchor){const b=player.getBounds();cancelMotion();resizeAnchor={right:b.x+b.width,top:b.y};}
  resizeTarget=width;if(resizeTimer)return;resizeRunning=true;
  const begin=performance.now();resizeState={width:player.getBounds().width,velocity:0,previous:begin,frames:0,samples:[]};
  // Retarget one continuous animation. No queue of independent resize requests.
  resizeStep=()=>{
    if(!validWindow(player)||!resizeState||!resizeAnchor)return cancelMotion();
    const now=performance.now();if(now-resizeState.previous<3)return;const dt=Math.min(.05,Math.max(.001,(now-resizeState.previous)/1000));resizeState.previous=now;
    const delta=resizeState.width-resizeTarget,b=resizeState.velocity+42*delta,decay=Math.exp(-42*dt);
    resizeState.width=resizeTarget+(delta+b*dt)*decay;resizeState.velocity=(resizeState.velocity-42*b*dt)*decay;
    const done=Math.abs(resizeState.width-resizeTarget)<.25&&Math.abs(resizeState.velocity)<8,w=done?resizeTarget:Math.round(resizeState.width),h=Math.round(w*9/16),bounds=confine({x:resizeAnchor.right-w,y:resizeAnchor.top,width:w,height:h},area()),current=player.getBounds();
    if(Object.keys(bounds).some(key=>bounds[key]!==current[key])){player.setBounds(bounds,false);updateShape();send(player,'moro:resize-viewport',player.getBounds());resizeState.samples.push({ms:now-begin,...player.getBounds()});}
    resizeState.frames++;
    if(done){lastResizeReport={completed:true,frames:resizeState.frames,changes:resizeState.samples.length,failures:0,durationMs:now-begin,samples:resizeState.samples};resizeState=null;finishResize();}
  };resizeTimer=setInterval(()=>{if(resizeState&&performance.now()-resizeState.previous>28)resizeStep?.();},16);send(player,'moro:resize-clock',true);
}
function applySettings(next){const oldWidth=settings.width,oldRadius=settings.radius;if(!settings.gooPinned&&next.gooPinned&&dock)next={...next,gooX:dock.point.x,gooY:dock.point.y};settings=sanitizeSettings(next);if(oldWidth!==settings.width&&validWindow(player))resizePlayer(Math.min(settings.width,area().width-36));if(oldRadius!==settings.radius&&!resizeRunning)updateShape();if(validWindow(player))player.setOpacity(settings.opacity/100);placeController();send(player,'moro:settings',settings);send(controller,'moro:settings',settings);persist();}
async function operation(action,value){if(!validWindow(player))return {ok:false,message:'The player is still loading'};return player.webContents.executeJavaScript(`(${playerOperation.toString()})(${JSON.stringify(action)},${JSON.stringify(value??null)})`,true);}
async function loadDemo(){const generation=++mediaGeneration;kind='demo';cancelMotion();controllerOpen=false;setDockVisible(false);await player.loadFile(path.join(__dirname,'ui/player.html'));if(generation!==mediaGeneration)return;await operation('demo',{src:assets('flower.mp4')});setPlayerVisible(true,true);}
async function loadVideo(id){const generation=++mediaGeneration;kind='youtube';cancelMotion();controllerOpen=false;setPlayerVisible(true,!smoke&&!youtubeProbe);setDockVisible(false);try{await player.loadURL(`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&controls=0&enablejsapi=1&playsinline=1&rel=0&hl=en`,{httpReferrer:{url:'https://moro.local/',policy:'strict-origin-when-cross-origin'}});}catch(error){if(generation!==mediaGeneration||!validWindow(player)||closing)return;kind='empty';await player.loadFile(path.join(__dirname,'ui/player.html'));send(player,'moro:notice','Could not open YouTube. Check your connection and try the link again.');notice('Could not open YouTube: '+error.code);}}
function secure(w){w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-attach-webview',e=>e.preventDefault());w.webContents.on('will-navigate',(e,url)=>{if(w===controller||!/^https:\/\/www\.youtube-nocookie\.com\/embed\/[\w-]{11}(\?|$)/.test(url))e.preventDefault();});}
async function createWindows(){
  Menu.setApplicationMenu(null);
  try{settings=sanitizeSettings(JSON.parse(fs.readFileSync(settingsFile(),'utf8')));}catch{}
  const a=screen.getPrimaryDisplay().workArea,width=Math.min(settings.width,a.width-36),height=Math.round(width*9/16);
  const options={frame:false,transparent:true,backgroundColor:'#00000000',thickFrame:false,maximizable:false,fullscreenable:false,hasShadow:false,roundedCorners:true,alwaysOnTop:true,show:false,icon:path.join(__dirname,'assets/moro.ico')};
  player=new BrowserWindow({...options,title:'Moro',width,height,x:a.x+a.width-width-28,y:a.y+a.height-height-28,minWidth:320,minHeight:180,resizable:false,minimizable:false,skipTaskbar:true,webPreferences:{preload:path.join(__dirname,'player-preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
  controller=new BrowserWindow({...options,title:'Moro — controls',width:400,height:600,resizable:false,skipTaskbar:true,webPreferences:{preload:path.join(__dirname,'controller-preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
  player.setAlwaysOnTop(true,'floating');controller.setAlwaysOnTop(true,'floating');player.setOpacity(settings.opacity/100);updateShape();placeController();secure(player);secure(controller);
  const nativeRoot=app.isPackaged?path.join(process.resourcesPath,'app.asar.unpacked','native'):path.join(__dirname,'native');motionDriver=new NativeMotion(path.join(nativeRoot,'MoroMotion.exe'));if(!smoke&&!youtubeProbe)motionDriver.onKeys=setControlHeld;await motionDriver.ready;if(motionDriver.available)desktopProtection=await motionDriver.protect(player.getNativeWindowHandle().readBigUInt64LE().toString());
  controller.setIgnoreMouseEvents(false);controller.setShape([{x:Math.max(0,controller.getBounds().width-70),y:controller.getBounds().height-38,width:60,height:30}]);
  updateInteraction(undefined,true);
  if(smoke||youtubeProbe)for(const w of [player,controller])w.webContents.on('console-message',event=>console.log('[renderer]',event.message));
  player.on('close',e=>{if(!closing)e.preventDefault();});
  player.on('minimize',()=>setImmediate(preservePlayerVisibility));
  player.on('hide',()=>{send(player,'moro:hover',false);placeController();setDockVisible(true);setImmediate(preservePlayerVisibility);});
  player.on('show',()=>setDockVisible(true));
  controller.on('close',e=>{if(!closing){e.preventDefault();controller.hide();}});
  controller.on('blur',()=>{if(controllerOpen){controllerOpen=false;send(controller,'moro:dismiss');setDockVisible(true);}});
  player.on('moved',()=>{if(!drag&&!spring&&!resizeRunning)placeController();});
  // WM_ENTERSIZEMOVE / WM_EXITSIZEMOVE bracket Windows' own compositor move loop.
  player.hookWindowMessage(0x0231,beginDrag);player.hookWindowMessage(0x0232,endDrag);
  player.hookWindowMessage(0x001f,endDrag);
  session.defaultSession.setPermissionRequestHandler((_wc,_permission,callback)=>callback(false));session.defaultSession.setPermissionCheckHandler(()=>false);
  await Promise.all([player.loadFile(path.join(__dirname,'ui/player.html')),controller.loadFile(path.join(__dirname,'ui/controller.html'))]);
  setDockVisible(true);
  tray=new Tray(nativeImage.createFromPath(path.join(__dirname,'assets/moro.png')));tray.setToolTip('Moro — YouTube PiP');tray.setContextMenu(Menu.buildFromTemplate([{label:'Add video',click:presentController},{label:'Show video',click:()=>setPlayerVisible(true)},{label:'Hide video',click:()=>setPlayerVisible(false)},{type:'separator'},{label:'Quit Moro',click:()=>app.quit()}]));tray.on('click',presentController);
  screen.on('display-removed',()=>{cancelMotion();player.setBounds(confine(player.getBounds(),screen.getPrimaryDisplay().workArea),false);placeController();});screen.on('display-metrics-changed',()=>{cancelMotion();player.setBounds(confine(player.getBounds(),area()),false);placeController();});
  setInterval(()=>{if(!validWindow(player)||!validWindow(controller))return;preservePlayerVisibility();const cursor=screen.getCursorScreenPoint();
    if(!smoke&&!youtubeProbe)updateInteraction(cursor);
    if(!smoke&&!youtubeProbe)setDockVisible(!drag&&!spring);
  },30);
  setInterval(async()=>{if(pollBusy||!validWindow(player)||player.webContents.isLoadingMainFrame())return;pollBusy=true;try{lastState=await operation('state');send(player,'moro:state',lastState);}catch{}finally{pollBusy=false;}},300);
}
ipcMain.handle('moro:bootstrap',e=>trustedPlayer(e)?{kind,settings,css:playerCSS,tree:JSON.parse(fs.readFileSync(path.join(__dirname,'ui/overlay-tree.json'),'utf8'))}:null);
ipcMain.on('moro:resize-tick',e=>{if(trustedPlayer(e))resizeStep?.();});
ipcMain.on('moro:overlay-ready',e=>{if(trustedPlayer(e)){send(player,'moro:settings',settings);updateInteraction(undefined,true);}});
let controllerShapeSignature='';
ipcMain.on('moro:hit-regions',(e,rects)=>{if(!trustedController(e)||!Array.isArray(rects))return;const b=controller.getBounds();hitRegions=rects.slice(0,10).filter(r=>['x','y','width','height'].every(k=>Number.isFinite(r[k]))&&r.width>0&&r.height>0&&r.width<=410&&r.height<=600).map(r=>{const x=Math.max(0,Math.floor(r.x)),y=Math.max(0,Math.floor(r.y));return {x,y,width:Math.max(1,Math.min(b.width-x,Math.ceil(r.width))),height:Math.max(1,Math.min(b.height-y,Math.ceil(r.height)))};});const signature=JSON.stringify(hitRegions);if(hitRegions.length&&signature!==controllerShapeSignature){controllerShapeSignature=signature;controller.setShape(hitRegions);}});
ipcMain.on('moro:controller-state',(e,open)=>{if(trustedController(e)){controllerOpen=open===true;controllerLastSeen=Date.now();setDockVisible(true);}});
ipcMain.handle('moro:player-action',async(e,action,value)=>{
  if(!trustedPlayer(e))return {ok:false};
  if(action==='hide'){setPlayerVisible(false);return {ok:true};}
  if(!['play','seek','volume','mute','rate','quality','audio'].includes(action))return {ok:false};
  if(action==='seek'&&(!Number.isFinite(value)||value<0||value>604800))return {ok:false};
  if(action==='volume'&&(!Number.isFinite(value)||value<0||value>100))return {ok:false};
  if(action==='rate'&&![.5,.75,1,1.25,1.5,2].includes(value))return {ok:false};
  if(action==='quality'){if(typeof value!=='string'||!['auto','tiny','small','medium','large','hd720','hd1080','hd1440','hd2160','highres','540','360'].includes(value))return {ok:false};if(kind==='demo')value={id:value,src:assets(value==='360'?'flower-360.mp4':'flower.mp4')};}
  if(action==='audio'&&(typeof value!=='string'||value.length>256))return {ok:false};
  try{return await operation(action,value);}catch{return {ok:false,message:'This action is not available yet'};}
});
ipcMain.handle('moro:control',async(e,action,value)=>{
  if(!trustedController(e)&&!trustedPlayer(e))return {ok:false};
  if(action==='init'){dockSignature='';publishDock();return {settings};}
  if(action==='clipboard'){if(!trustedController(e))return {url:''};const text=clipboard.readText();return {url:parseYouTube(text)?text:''};}
  if(action==='resize-gesture'){resizeGesture=value===true;if(resizeGesture){cancelMotion();const b=player.getBounds();resizeAnchor={right:b.x+b.width,top:b.y};}if(!resizeGesture&&!resizeRunning)finishResize();if(resizeGesture)updateInteraction(undefined,true);else interactionSignature='';return {ok:true};}
  if(action==='settings'){if(!value||typeof value!=='object'||Array.isArray(value))return {ok:false};applySettings({...settings,...value});return {ok:true};}
  if(action==='reset'){applySettings(defaults);center();return {ok:true};}
  if(action==='load'){const id=parseYouTube(value);if(!id)return {ok:false,message:'Enter a link to a specific YouTube video'};loadVideo(id).catch(()=>notice('Could not open the video'));return {ok:true};}
  if(action==='demo'){await loadDemo();return {ok:true};}
  if(action==='visibility'){if(kind==='empty')return {ok:false,message:'Add a video link first'};setPlayerVisible(!playerWanted);return {ok:true};}
  if(action==='center'){center();return {ok:true};}
  if(action==='monitor'){const displays=screen.getAllDisplays(),current=screen.getDisplayMatching(player.getBounds()),index=displays.findIndex(d=>d.id===current.id),next=displays[(index+1)%displays.length];cancelMotion();const a=next.workArea;player.setBounds(confine({...player.getBounds(),x:a.x+a.width-player.getBounds().width-18,y:a.y+a.height-player.getBounds().height-18},a),false);placeController(next);if(kind!=='empty')setPlayerVisible(true);return {ok:true,message:displays.length===1?'Only one display is connected':undefined};}
  if(action==='clear'){const generation=++mediaGeneration;kind='empty';cancelMotion();await player.loadFile(path.join(__dirname,'ui/player.html'));if(generation===mediaGeneration)setPlayerVisible(false);return {ok:true};}
  if(action==='video-settings'){if(kind==='empty')return {ok:false,message:'Add a video first'};setPlayerVisible(true,true);send(player,'moro:menu');return {ok:true};}
  if(action==='quit'){app.quit();return {ok:true};}return {ok:false};
});
app.on('second-instance',()=>{if(validWindow(controller))presentController();});
app.on('before-quit',()=>{closing=true;cancelMotion();motionDriver?.dispose();clearTimeout(saveTimer);try{fs.writeFileSync(settingsFile(),JSON.stringify(settings,null,2));}catch{}});
app.on('window-all-closed',()=>app.quit());
app.whenReady().then(async()=>{await createWindows();if(inputCheck)await inspectInput();else if(smoke||youtubeProbe)await runCheck();else{const openIndex=process.argv.indexOf('--open-url'),id=openIndex>=0?parseYouTube(process.argv[openIndex+1]):null;if(id)await loadVideo(id);else if(process.argv.includes('--show-launcher'))presentController();}}).catch(e=>{console.error(e);app.exit(1);});
async function inspectInput(){fs.mkdirSync(reportDir,{recursive:true});const errors=[];for(const w of [controller,player])w.webContents.on('console-message',e=>errors.push(e.message));setInterval(async()=>{try{const result={errors,kind,drag,spring:!!spring,hover,controllerVisible,hitRegions,dock,controllerBounds:controller.getBounds(),playerBounds:player.getBounds()};for(const [name,w]of [['controller',controller],['player',player]])result[name]=await w.webContents.executeJavaScript("({bodyClass:document.body.className,buttons:[...document.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect(),s=getComputedStyle(b);return {id:b.id,x:r.x,y:r.y,width:r.width,height:r.height,pointer:s.pointerEvents,visibility:s.visibility,display:s.display,region:s.getPropertyValue('-webkit-app-region'),hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.id}})})");fs.writeFileSync(path.join(reportDir,'input.json'),JSON.stringify(result,null,2));}catch{}},1000);}
async function runCheck(){const sleep=ms=>new Promise(r=>setTimeout(r,ms));const assert=(ok,text)=>{if(!ok)throw new Error(text);};fs.mkdirSync(reportDir,{recursive:true});const result={version:app.getVersion(),packaged:app.isPackaged,platform:process.platform,checks:[]};
  async function clickButton(w,id){const target=await w.webContents.executeJavaScript(`(()=>{const key=${JSON.stringify(id)},b=key.startsWith('#')?document.querySelector(key):document.getElementById(key);if(key.startsWith('#'))b.scrollIntoView({block:'nearest'});const r=b.getBoundingClientRect(),s=getComputedStyle(b),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2),width:r.width,height:r.height,pointer:s.pointerEvents,visibility:s.visibility,region:s.getPropertyValue('app-region'),hit:hit?.closest('button')===b}})()`);assert(target.width>0&&target.height>0&&target.visibility==='visible'&&target.pointer==='auto'&&target.hit,'button must be hit-testable: '+id);if(w===player){assert(target.region==='no-drag','interactive player region must not drag: '+id);const b=w.getBounds(),native=await motionDriver.inspect(w.getNativeWindowHandle().readBigUInt64LE().toString(),screen.dipToScreenPoint({x:b.x+target.x,y:b.y+target.y}));(result.nativeButtons??=[]).push({button:id,...native});assert(native.hitCode===1&&!native.transparent,'Windows must deliver a client click, not a move: '+id+' '+native.hitCode);}w.webContents.sendInputEvent({type:'mouseMove',x:target.x,y:target.y});w.webContents.sendInputEvent({type:'mouseDown',x:target.x,y:target.y,button:'left',clickCount:1});w.webContents.sendInputEvent({type:'mouseUp',x:target.x,y:target.y,button:'left',clickCount:1});await sleep(160);}
  async function checkInteraction(){const b=player.getBounds(),inside={x:b.x+b.width/2,y:b.y+b.height/2};setControlHeld(false);updateInteraction(inside,true);await sleep(230);const handle=player.getNativeWindowHandle().readBigUInt64LE().toString();result.passiveInput=await motionDriver.inspect(handle,screen.dipToScreenPoint(inside));result.passiveUI=await player.webContents.executeJavaScript("({opacity:getComputedStyle(document.body).opacity,controls:getComputedStyle(document.getElementById('apple-controls')).opacity})");assert(result.passiveInput.transparent&&result.passiveUI.opacity==='0.82'&&result.passiveUI.controls==='0','passive hover fades and passes through without opening controls');for(let i=0;i<6;i++)player.webContents.sendInputEvent({type:'mouseMove',x:90+i*12,y:100});await sleep(80);assert(await player.webContents.executeJavaScript("getComputedStyle(document.getElementById('apple-controls')).opacity==='0'"),'pointer moves alone never reveal controls');setControlHeld(true);updateInteraction(inside,true);await sleep(230);result.activeInput=await motionDriver.inspect(handle,screen.dipToScreenPoint(inside));assert(!result.activeInput.transparent&&!controller.isVisible(),'Ctrl makes only the video interactive, no desktop tab');assert(result.activeInput.hitCode===2,'Windows must recognize the free video area as a native drag region');assert(await player.webContents.executeJavaScript("getComputedStyle(document.body).opacity==='1'&&getComputedStyle(document.getElementById('apple-controls')).opacity==='1'"),'Ctrl restores opacity and reveals controls');result.checks.push('passive hover fades to 82%, native click-through enabled; pointer movement cannot reveal UI; Ctrl restores interactive video without desktop tab');result.desktopProtection=desktopProtection;assert(desktopProtection?.peekDisabled&&desktopProtection?.peekExcluded&&desktopProtection?.transitionsDisabled,'native DWM desktop protection is installed');player.setMinimizable(true);player.minimize();await sleep(200);assert(player.isVisible()&&!player.isMinimized(),'system minimization cannot leave the video minimized');player.setMinimizable(false);player.hide();await sleep(200);assert(player.isVisible(),'system hiding is restored while video is wanted');player.close();await sleep(120);assert(player.isVisible()&&!player.isDestroyed(),'OS close requests cannot dismiss video');setPlayerVisible(false);await sleep(120);assert(!player.isVisible(),'intentional tray/close hiding remains hidden');setPlayerVisible(true);updateInteraction(inside,true);await sleep(200);result.checks.push('DWM Peek exclusions installed; native minimize/hide/close requests preserve video; intentional hide remains hidden');}
  async function checkNativeDrag(){
    const {spawn}=require('node:child_process');result.nativeDrag=[];
    for(const mode of ['free','edge']){
      const a=area();player.setPosition(mode==='free'?a.x+620:a.x+260,mode==='free'?a.y+260:a.y+170,false);
      const before=player.getBounds(),stateBefore=await operation('state'),sampleFile=path.join(reportDir,'native-drag-'+mode+'.json');
      await new Promise((resolve,reject)=>{const handle=player.getNativeWindowHandle().readBigUInt64LE().toString();const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(__dirname,'tools/drag-window.ps1'),'-WindowHandle',handle,'-ReportPath',sampleFile,'-DeltaX',mode==='free'?'252':'-210','-DeltaY',mode==='free'?'72':'-132'],{windowsHide:true,stdio:'pipe'});let error='';child.stderr.on('data',chunk=>error+=chunk);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error(error)));});
      const after=player.getBounds(),stateAfter=await operation('state'),trace=JSON.parse(fs.readFileSync(sampleFile,'utf8').replace(/^\uFEFF/,'')),samples=trace.samples,moving=samples.filter(s=>s.phase==='drag'),release=samples.filter(s=>s.phase==='release'),unique=new Set(moving.map(s=>`${s.x},${s.y}`)).size;
      const last=moving.at(-1),maxReleaseStep=Math.max(...release.map((s,i)=>{const prev=i?release[i-1]:last;return Math.hypot(s.x-prev.x,s.y-prev.y);})),maxReleaseVelocity=Math.max(...release.map((s,i)=>{const prev=i?release[i-1]:last;return Math.hypot(s.x-prev.x,s.y-prev.y)/Math.max(1,s.ms-prev.ms)*1000;}));
      result.nativeDrag.push({mode,before,after,uniquePositions:unique,sampleCount:samples.length,maxReleaseStep,maxReleaseVelocity,region:trace.region,stateBefore,stateAfter,nativeMotion:mode==='edge'?motionDriver.lastReport:null});
      assert(unique>=18,'Windows drag geometry must update throughout movement');assert(stateAfter.playing===stateBefore.playing,'drag release must preserve playback');
      assert(!trace.region.thickFrame&&trace.region.center&&['topLeft','topRight','bottomLeft','bottomRight'].every(k=>!trace.region[k]),'native region clips all corners without a DWM frame');
      if(mode==='free')assert(release.every(s=>s.x===release[0].x&&s.y===release[0].y),'free drag must stay exactly at its released position');
      else{assert(nearest(after,area()).d<=1.5,'edge release must settle at its magnet');assert(maxReleaseVelocity<500,'edge docking must approach smoothly without a teleport');assert(release.every((s,i)=>{const previous=i?release[i-1]:last;return s.x<=previous.x&&s.y<=previous.y&&s.x>=after.x&&s.y>=after.y;}),'zero-bounce docking must not overshoot or reverse');}
    }
    result.checks.push('real Windows drag and release: free placement stays put, edge docking has no position jump, playback preserved, all native corners clipped');
  }
  try{
    assert(motionDriver.available,'native motion worker must be ready');
    await sleep(700);assert(player.isAlwaysOnTop(),'player must be on top');result.checks.push('native Windows windows, transparent, frameless, always on top');
    assert(!controller.isVisible()&&!player.isVisible(),'launch has no persistent circle or blank window');
    setControlHeld(true);await sleep(80);assert(!controller.isVisible(),'Ctrl must not open a desktop handle');setControlHeld(false);presentController();await sleep(650);assert(controller.isVisible()&&controllerOpen,'tray opens the compact URL form');assert(await controller.webContents.executeJavaScript("getComputedStyle(document.getElementById('goo-toggle')).display==='none'"),'desktop handle has been removed');result.checks.push('no desktop handle or Ctrl + Alt launcher; tray opens a compact link form');
    await controller.webContents.executeJavaScript("document.getElementById('url').value='not a valid URL'");await clickButton(controller,'#url-form button');
    result.invalidUrl=await controller.webContents.executeJavaScript("({custom:document.getElementById('url-form').noValidate,message:document.getElementById('url-help').textContent,error:document.getElementById('url-help').classList.contains('error')})");assert(result.invalidUrl.custom&&result.invalidUrl.error&&result.invalidUrl.message==='Enter a link to a specific YouTube video','invalid URL uses English app validation instead of OS language');result.checks.push('malformed URL submission shows custom English error without native validation popup');
    await controller.webContents.executeJavaScript("const field=document.getElementById('url');field.value='';field.focus()");await controller.webContents.insertText(probeUrl);
    result.urlSurface=await controller.webContents.executeJavaScript("(()=>{const field=document.getElementById('url'),s=getComputedStyle(field);return {radius:s.borderRadius,outline:s.outlineStyle,clip:s.clipPath,value:field.value,focused:document.activeElement===field}})()");
    assert(result.urlSurface.radius==='12px'&&result.urlSurface.outline==='none'&&result.urlSurface.focused&&result.urlSurface.clip.includes('12px'),'pasted link preserves rounded input focus');
    await sleep(120);fs.writeFileSync(path.join(reportDir,'launch.png'),(await controller.webContents.capturePage()).toPNG());
    assert(await controller.webContents.executeJavaScript("!document.getElementById('goo-url-panel').hidden"),'URL popover');result.checks.push('Gooey launch → URL popover');
    if(youtubeProbe){
      await controller.webContents.executeJavaScript("document.getElementById('url-form').requestSubmit()");await sleep(16000);result.youtube=await operation('state');assert(result.youtube.ready&&result.youtube.playing&&result.youtube.time>0,'YouTube playback');result.checks.push('paste URL → submit Gooey form → actual YouTube playback');
      result.sourceUrl=probeUrl;await checkInteraction();await clickButton(player,'apple-play');await sleep(400);result.youtubePaused=await operation('state');assert(!result.youtubePaused.playing,'pointer click must actually pause this YouTube video');await clickButton(player,'apple-play');await sleep(800);result.youtubeResumed=await operation('state');assert(result.youtubeResumed.playing,'pointer click must actually resume this YouTube video');result.checks.push('actual pointer events pause and resume the supplied YouTube video');
      if(nativeDrag)await checkNativeDrag();
      send(player,'moro:hover',true);await clickButton(player,'apple-settings');await sleep(450);fs.writeFileSync(path.join(reportDir,'embedded-fan.png'),(await player.webContents.capturePage()).toPNG());await clickButton(player,'goo-video-toggle');await sleep(450);
      const quality=result.youtube.qualities.includes('hd1080')?'hd1080':result.youtube.qualities.find(q=>q!=='auto');assert(quality,'video provides quality choices');result.requestedQuality=quality;await clickButton(player,`#quality-options button[data-option=${quality}]`);await sleep(5000);result.youtubeAfterQuality=await operation('state');assert(result.youtubeAfterQuality.quality===quality,'YouTube quality acknowledgment');result.checks.push('pointer click in own menu changes actual YouTube quality');
      const tracks=result.youtubeAfterQuality.audio,chosen=tracks.find(t=>t.name.includes('Russian')&&t.id!==result.youtubeAfterQuality.audioId)||tracks.find(t=>t.id!==result.youtubeAfterQuality.audioId);if(chosen){await clickButton(player,`#audio-options button[data-option=${JSON.stringify(chosen.id)}]`);await sleep(4000);result.youtubeAfterAudio=await operation('state');assert(result.youtubeAfterAudio.audioId===chosen.id,'YouTube audio acknowledgment');result.checks.push('pointer click in own menu changes actual YouTube audio');}else result.audioNote='Video provides no alternate audio track';
      send(player,'moro:menu');await sleep(300);
      result.youtubeUI=await player.webContents.executeJavaScript("({bodyClass:document.body.className,htmlClass:document.documentElement.className,uiClass:document.getElementById('moro-ui')?.className,menuHidden:document.getElementById('video-settings')?.hidden,nativeMenuDisplay:document.querySelector('.ytp-settings-menu')&&getComputedStyle(document.querySelector('.ytp-settings-menu')).display,topDisplay:document.querySelector('.ytp-chrome-top')&&getComputedStyle(document.querySelector('.ytp-chrome-top')).display,newControlsDisplay:document.querySelector('.player-controls-content')&&getComputedStyle(document.querySelector('.player-controls-content')).display})");
      fs.writeFileSync(path.join(reportDir,'youtube-menu.png'),(await player.webContents.capturePage()).toPNG());
      assert([null,'none'].includes(result.youtubeUI.nativeMenuDisplay)&&[null,'none'].includes(result.youtubeUI.topDisplay)&&[null,'none'].includes(result.youtubeUI.newControlsDisplay),'native chrome replaced');
      send(player,'moro:hover',true);await sleep(400);fs.writeFileSync(path.join(reportDir,'youtube.png'),(await player.webContents.capturePage()).toPNG());
    }
    else{
      await controller.webContents.executeJavaScript("document.getElementById('goo-demo').click()");await sleep(1600);let s=await operation('state');result.initialPlayback=s;result.mediaDiagnostics=await player.webContents.executeJavaScript("({url:location.href,src:document.querySelector('video')?.src,network:document.querySelector('video')?.networkState,error:document.querySelector('video')?.error?.message})");assert(s.ready&&s.playing&&s.time>0,'demo must play');result.checks.push('Gooey → actual video playback with moving time');
      await checkInteraction();
      if(nativeDrag)await checkNativeDrag();
      send(player,'moro:hover',true);await sleep(350);await clickButton(player,'apple-play');await sleep(200);s=await operation('state');assert(!s.playing,'pause');await operation('seek',2);s=await operation('state');assert(Math.abs(s.time-2)<.15,'seek');await player.webContents.executeJavaScript("const volume=document.getElementById('apple-volume');volume.value=35;volume.dispatchEvent(new Event('input'));document.getElementById('apple-rate').click()");await sleep(200);s=await operation('state');assert(s.volume===35&&!s.muted&&s.rate===1.25,'volume/rate');result.checks.push('player UI receives pointer clicks, pauses, seeks, changes volume and speed');
      send(player,'moro:hover',true);await player.webContents.executeJavaScript("document.getElementById('apple-settings').click()");await sleep(450);fs.writeFileSync(path.join(reportDir,'embedded-fan.png'),(await player.webContents.capturePage()).toPNG());await player.webContents.executeJavaScript("document.getElementById('goo-video-toggle').click()");await sleep(400);await player.webContents.executeJavaScript("document.querySelector('#quality-options button[data-option=\"360\"]').click()");await sleep(700);const video=await player.webContents.executeJavaScript("({width:document.getElementById('demo-video').videoWidth,time:document.getElementById('demo-video').currentTime,paused:document.getElementById('demo-video').paused})");assert(video.width===640&&Math.abs(video.time-2)<.15&&video.paused,'real quality switch');result.checks.push('… → Gooey → video settings changes actual 540p to 360p, preserving time and pause');
      const b=player.getBounds();player.setPosition(b.x+7,b.y+7);moveTo(nearest(player.getBounds(),area()));await sleep(2600);const snapped=nearest(player.getBounds(),area());result.snap={bounds:player.getBounds(),target:snapped};assert(snapped.d<=1.5,'magnet');result.checks.push('native window magnetic snap completes within one DPI pixel');
      applySettings({...settings,width:520,tint:34,blur:23});await sleep(450);result.resizeDiagnostics={bounds:player.getBounds(),settings,animation:lastResizeReport};assert(player.getBounds().width===520,'resize');result.checks.push('native size and saved glass settings');
      send(player,'moro:menu');await sleep(300);fs.writeFileSync(path.join(reportDir,'quality.png'),(await player.webContents.capturePage()).toPNG());
      send(player,'moro:hover',false);await sleep(300);const hidden=await player.webContents.executeJavaScript("getComputedStyle(document.querySelector('#apple-controls')).opacity");assert(hidden==='0','hidden controls');result.checks.push('controls disappear outside player');fs.writeFileSync(path.join(reportDir,'video-clean.png'),(await player.webContents.capturePage()).toPNG());
      send(player,'moro:hover',true);await sleep(350);fs.writeFileSync(path.join(reportDir,'video-controls.png'),(await player.webContents.capturePage()).toPNG());
      const metrics=await player.webContents.executeJavaScript("({drag:getComputedStyle(document.getElementById('moro-drag-surface')).getPropertyValue('app-region'),play:getComputedStyle(document.getElementById('apple-play')).width,track:getComputedStyle(document.getElementById('apple-progress'),'::-webkit-slider-runnable-track').height,thumb:getComputedStyle(document.getElementById('apple-progress'),'::-webkit-slider-thumb').marginTop,toastBlur:getComputedStyle(document.getElementById('native-status')).backdropFilter})");result.metrics=metrics;assert(metrics.drag==='drag'&&metrics.play==='40px'&&metrics.toastBlur.includes('blur'),'native drag and glass UI');
      result.state=await operation('state');result.bounds=player.getBounds();result.display=area();result.hitRegions=hitRegions;
    }
    const motionStart=player.getBounds();player.setPosition(motionStart.x+70,motionStart.y+40);moveTo(motionStart);const motionRequest=spring;assert(motionRequest?.finished,'snap must use the native motion worker');result.nativeMotion=await motionRequest.finished;assert(result.nativeMotion.completed&&result.nativeMotion.failures===0,'native magnetic movement must finish without a Win32 failure');assert(result.nativeMotion.p95Ms<40,'native movement update intervals must not resemble 15 fps');result.checks.push('native motion worker completes docking; actual movement update intervals recorded');
    assert(!controller.isVisible()&&!controllerVisible&&hitRegions.length===0,'playing video must have no desktop orb or external hit regions');
    send(player,'moro:hover',false);await sleep(220);send(player,'moro:hover',true);await sleep(220);
    const beforeGoo=await operation('state');await clickButton(player,'apple-settings');await sleep(500);
    result.fan=await player.webContents.executeJavaScript("(()=>{const root=document.getElementById('moro-ui'),main=document.getElementById('goo-toggle').getBoundingClientRect(),anchor=document.getElementById('apple-settings').getBoundingClientRect();return {open:root.classList.contains('goo-open'),anchorDistance:Math.hypot(main.x+main.width/2-anchor.x-anchor.width/2,main.y+main.height/2-anchor.y-anchor.height/2),buttons:[...document.querySelectorAll('#goo-wrap .goo-control')].map(b=>{const r=b.getBoundingClientRect();return {id:b.id,x:r.x,y:r.y,right:r.right,bottom:r.bottom}}),width:innerWidth,height:innerHeight}})()");
    assert(result.fan.open&&result.fan.anchorDistance<1.5,'Gooey must unfold from the transport … button');assert(result.fan.buttons.every(b=>b.x>=0&&b.y>=0&&b.right<=result.fan.width&&b.bottom<=result.fan.height),'fan fits inside the video');assert((await operation('state')).playing===beforeGoo.playing,'opening management preserves playback');
    result.gooRouting=await player.webContents.executeJavaScript("({videoClass:document.getElementById('goo-video-toggle').className,interfaceClass:document.getElementById('goo-settings-toggle').className,tooltips:document.querySelectorAll('#moro-ui [title],#moro-ui .goo-tooltip').length})");assert(result.gooRouting.videoClass.includes('sub b')&&result.gooRouting.interfaceClass.includes('sub c')&&result.gooRouting.tooltips===0,'gear opens video settings, upper sliders open interface settings, no hover labels');assert(await controller.webContents.executeJavaScript("document.querySelectorAll('[title],.goo-tooltip').length===0"),'launcher has no hover labels');
    result.liquidFilter=await player.webContents.executeJavaScript("({blur:document.querySelector('#goo-filter feGaussianBlur').constructor.name,matrix:document.querySelector('#goo-filter feColorMatrix').constructor.name})");assert(result.liquidFilter.blur==='SVGFEGaussianBlurElement'&&result.liquidFilter.matrix==='SVGFEColorMatrixElement','liquid mask must contain real SVG filter primitives');
    await clickButton(player,'goo-settings-toggle');await sleep(250);
    const sizeTrack=await player.webContents.executeJavaScript("(()=>{const w=document.getElementById('width'),r=w.getBoundingClientRect();return {left:window.screenX+r.left,width:r.width,y:window.screenY+r.top+r.height/2,value:+w.value,min:+w.min,max:+w.max}})()");
    const thumbX=sizeTrack.left+5+(sizeTrack.width-10)*(sizeTrack.value-sizeTrack.min)/(sizeTrack.max-sizeTrack.min),sizeBefore=player.getBounds(),sizePlayback=await operation('state');
    const pointerAt=async(x,type='mouseMove')=>{const b=player.getBounds();player.webContents.sendInputEvent({type,x:Math.round(x-b.x),y:Math.round(sizeTrack.y-b.y),globalX:Math.round(x),globalY:Math.round(sizeTrack.y),...(type==='mouseMove'?{}:{button:'left',clickCount:1})});};
    await pointerAt(thumbX);await pointerAt(thumbX,'mouseDown');await sleep(60);result.liveResize=[];
    for(const shift of [8,16,24,32,16,0,-16,-36]){await pointerAt(thumbX+shift);await sleep(80);const panel=await player.webContents.executeJavaScript("new Promise(resolve=>requestAnimationFrame(()=>{const r=document.getElementById('width').getBoundingClientRect();resolve({x:window.screenX+r.left,y:window.screenY+r.top+r.height/2,value:+document.getElementById('width').value})}))");result.liveResize.push({bounds:player.getBounds(),panel});}
    assert(result.liveResize[1].bounds.width>sizeBefore.width+10,'video must grow while the size slider remains held');assert(result.liveResize.at(-1).bounds.width<result.liveResize[3].bounds.width-100,'video must also shrink smoothly while held');assert(result.liveResize.every(v=>Math.abs(v.panel.x-sizeTrack.left)<=2&&Math.abs(v.panel.y-sizeTrack.y)<=2),'size slider must remain fixed on the desktop during live resizing');await pointerAt(thumbX-36,'mouseUp');await sleep(450);assert(Math.abs(player.getBounds().width-settings.width)<=1,'live resize settles at the selected width');assert((await operation('state')).playing===sizePlayback.playing,'live resizing preserves playback');result.liveResizeMotion=lastResizeReport;assert(result.liveResizeMotion?.completed&&result.liveResizeMotion.changes>5&&result.liveResizeMotion.failures===0,'live resize must update across multiple window frames');result.checks.push('size slider stays fixed under pointer; video grows while held and settles smoothly without interrupting playback');
    await player.webContents.executeJavaScript("const w=document.getElementById('width');w.value=450;w.dispatchEvent(new Event('input',{bubbles:true}));const t=document.getElementById('tint');t.value=40;t.dispatchEvent(new Event('input',{bubbles:true}));const b=document.getElementById('blur');b.value=18;b.dispatchEvent(new Event('input',{bubbles:true}))");await sleep(450);assert(player.getBounds().width===450&&settings.tint===40&&settings.blur===18,'live size and embedded sliders update native settings');
    await player.webContents.executeJavaScript("const f=document.getElementById('hoverFade');f.value=60;f.dispatchEvent(new Event('input',{bubbles:true}))");await sleep(200);assert(settings.hoverFade===60,'hover transparency slider saves its value');const pb=player.getBounds(),pc={x:pb.x+100,y:pb.y+50};setControlHeld(false);updateInteraction(pc,true);await sleep(230);assert(await player.webContents.executeJavaScript("getComputedStyle(document.body).opacity==='0.4'"),'hover transparency slider changes actual passive video opacity');setControlHeld(true);updateInteraction(pc,true);await sleep(230);assert(await player.webContents.executeJavaScript("getComputedStyle(document.body).opacity==='1'"),'Ctrl restores normal opacity after adjusting hover transparency');applySettings({...settings,hoverFade:18});await sleep(100);result.checks.push('hover transparency slider changes passive opacity to 40%, Ctrl restores it, setting persists in state');send(player,'moro:hover',true);await clickButton(player,'apple-settings');await sleep(450);await clickButton(player,'goo-settings-toggle');await sleep(200);
    fs.writeFileSync(path.join(reportDir,'embedded-settings.png'),(await player.webContents.capturePage()).toPNG());
    result.panelSizes=[];for(const width of [320,450,960]){applySettings({...settings,width});await sleep(450);const bounds=await player.webContents.executeJavaScript("(()=>{const p=document.getElementById('goo-settings-panel'),r=p.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:innerWidth,height:innerHeight,scrolls:document.querySelector('.goo-settings-body').scrollHeight>document.querySelector('.goo-settings-body').clientHeight}})()");assert(bounds.x>=0&&bounds.y>=0&&bounds.right<=bounds.width&&bounds.bottom<=bounds.height,'embedded settings fit at each native window size');result.panelSizes.push(bounds);fs.writeFileSync(path.join(reportDir,'settings-'+width+'.png'),(await player.webContents.capturePage()).toPNG());}
    applySettings({...settings,width:450});await sleep(450);
    await clickButton(player,'settings-panel-close');await clickButton(player,'goo-link');await player.webContents.executeJavaScript("document.getElementById('url').value='not a valid URL'");await clickButton(player,'#url-form button');
    result.embeddedInvalidUrl=await player.webContents.executeJavaScript("({custom:document.getElementById('url-form').noValidate,message:document.getElementById('url-help').textContent,error:document.getElementById('url-help').classList.contains('error')})");assert(result.embeddedInvalidUrl.custom&&result.embeddedInvalidUrl.error&&result.embeddedInvalidUrl.message==='Enter a link to a specific YouTube video','embedded invalid URL also uses English app validation');result.checks.push('embedded link form shows the same English validation error');
    await player.webContents.executeJavaScript("document.getElementById('url').value='https://youtu.be/M7lc1UVf-VE'");await sleep(200);fs.writeFileSync(path.join(reportDir,'embedded-url.png'),(await player.webContents.capturePage()).toPNG());
    await player.webContents.executeJavaScript("window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");assert(await player.webContents.executeJavaScript("!document.getElementById('moro-ui').classList.contains('goo-open')&&document.getElementById('goo-url-panel').hidden"),'Escape closes the fan and link form');
    await player.webContents.executeJavaScript("document.getElementById('apple-settings').click()");send(player,'moro:hover',false);await sleep(220);assert(await player.webContents.executeJavaScript("!document.getElementById('moro-ui').classList.contains('goo-open')&&getComputedStyle(document.getElementById('apple-controls')).opacity==='0'"),'pointer exit hides all embedded controls');
    send(player,'moro:hover',true);await sleep(220);await clickButton(player,'native-close');await sleep(200);assert(!player.isVisible()&&!controller.isVisible(),'closing video leaves no permanent launcher');
    setPlayerVisible(true);updateInteraction({x:player.getBounds().x+100,y:player.getBounds().y+50},true);await sleep(200);assert(player.isVisible()&&!controller.isVisible()&&hitRegions.length===0,'tray show-video restores video without a launcher');
    result.checks.push('in-video Gooey accepts pointer clicks; sliders and link entry work, all sizes fit, Escape and pointer exit dismiss; restored video has no launcher');
    send(player,'moro:hover',true);player.webContents.sendInputEvent({type:'mouseMove',x:100,y:50});await sleep(250);
    result.closeSurface=await player.webContents.executeJavaScript("(()=>{const c=document.getElementById('native-close'),r=c.getBoundingClientRect(),root=document.getElementById('moro-ui'),s=getComputedStyle(root);return {background:getComputedStyle(c).backgroundColor,panelBackground:getComputedStyle(document.getElementById('settings-panel-close')).backgroundColor,blur:getComputedStyle(c).backdropFilter,top:r.top,right:innerWidth-r.right,width:r.width,height:r.height,clip:getComputedStyle(document.documentElement).clipPath,root:{width:root.getBoundingClientRect().width,padding:s.padding,margin:s.margin,maxWidth:s.maxWidth}}})()");
    assert(result.closeSurface.top===12&&result.closeSurface.right===12&&result.closeSurface.width===30&&result.closeSurface.height===30,'close button stays in top right after media navigation and resize');
    assert(result.closeSurface.clip.includes('round'),'page compositor also clips rounded corners');
    assert(result.closeSurface.blur.includes('18px'),'standalone close uses the configured glass blur');
    await clickButton(player,'apple-settings');await sleep(450);setControlHeld(false);const p=player.getBounds();updateInteraction({x:p.x+100,y:p.y+50},true);await sleep(230);assert(await player.webContents.executeJavaScript("!document.getElementById('moro-ui').classList.contains('goo-open')&&getComputedStyle(document.getElementById('apple-controls')).opacity==='0'"),'releasing Ctrl closes even a focused menu and hides controls');result.releasedInput=await motionDriver.inspect(player.getNativeWindowHandle().readBigUInt64LE().toString(),screen.dipToScreenPoint({x:p.x+100,y:p.y+50}));assert(result.releasedInput.transparent&&!result.releasedInput.hits,'released Ctrl restores native click-through');result.checks.push('Windows hit test reports client clicks for every tested video button; releasing Ctrl dismisses menu and routes clicks below the video');
    result.checks.push('rounded pasted URL field, consistent top-right close after load and resize');result.ok=true;
  }catch(e){result.ok=false;result.error=e.stack;console.error(e);}
  fs.writeFileSync(path.join(reportDir,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));motionDriver?.dispose();app.exit(result.ok?0:1);
}
}
